using LaTeXStrings
default_params=Dict(
    "emin" => -2,
    "emax" =>  2,
    "xmin" =>  0.0,
    "xmax" =>  3.0,
    "initial_band" => 10,
    "final_band"   => 80,
    "height" => "13cm",
    "width" =>  "15cm",
    "scale_only_axis" => false,
    "ax_width_plotwdos" => "4.5cm",
    "ax_lw" => "1.5pt",                
    "ax_size_minor_tick" => "1.0mm",  
    "ax_size_major_tick" => "2.0mm",   
    "ax_tick_scale"      => 1.2,
    "ax_labels_scale"    => 1.5,
    "ax_xmajorgrids"     => true,
    "ax_legend_position" => (1,0.01),
    "ax_legend_anchor"   => "south east",
    "ax_ylabel"          => L" $E-E_{F}$ (eV)",
    "ax_plot_line_width" => "1pt",
    "ax_plot_mark_scale" => 1,
    "ax_plot_title_scale"=> 3,
)